language: python

python:
    - "2.7"

env:
    - DJANGO_VERSION=1.6

install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements.txt

script:
    - "python manage.py test"
